robot_cfg:
  kinematics:
    add_object_link: false
    asset_root_path: robot/genie1
    base_link: genie1_mobile
    collision_link_names:
    - arm_l_base_link
    - arm_r_base_link
    - arm_l_link1
    - arm_l_link2
    - arm_l_link3
    - arm_l_link4
    - arm_l_link5
    - arm_l_link6
    - arm_l_end_link
    - arm_r_link1
    - arm_r_link2
    - arm_r_link3
    - arm_r_link4
    - arm_r_link5
    - arm_r_link6
    - arm_r_end_link
    - gripper_l_base_link
    - gripper_r_base_link
    collision_sphere_buffer: 0.0
    collision_spheres:
      arm_l_base_link:
      - center:
        - 0.0
        - 0.0
        - 0.027
        radius: 0.02
      arm_l_end_link:
      - center:
        - 0.0
        - 0.0
        - -0.013
        radius: 0.02
      arm_l_link1:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.073
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.033
        radius: 0.02
      arm_l_link2:
      - center:
        - 0.0
        - -0.086
        - 0.0
        radius: 0.02
      arm_l_link3:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.141
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.03
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.084
        radius: 0.02
      arm_l_link4:
      - center:
        - 0.0
        - -0.05
        - 0.0
        radius: 0.02
      arm_l_link5:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.093
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.031
        radius: 0.02
      arm_l_link6:
      - center:
        - 0.0
        - -0.065
        - 0.0
        radius: 0.02
      arm_r_base_link:
      - center:
        - 0.0
        - 0.0
        - 0.027
        radius: 0.02
      arm_r_end_link:
      - center:
        - 0.004
        - 0.007
        - -0.019
        radius: 0.02
      arm_r_link1:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.073
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.033
        radius: 0.02
      arm_r_link2:
      - center:
        - 0.0
        - -0.086
        - 0.0
        radius: 0.02
      arm_r_link3:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.141
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.03
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.084
        radius: 0.02
      arm_r_link4:
      - center:
        - 0.0
        - -0.05
        - 0.0
        radius: 0.02
      arm_r_link5:
      - center:
        - 0.0
        - 0.0
        - 0.0
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.093
        radius: 0.02
      - center:
        - 0.0
        - 0.0
        - -0.031
        radius: 0.02
      arm_r_link6:
      - center:
        - 0.0
        - -0.065
        - 0.0
        radius: 0.02
      gripper_l_base_link:
      - center:
        - -0.066
        - 0.003
        - 0.122
        radius: 0.01
      - center:
        - 0.057
        - -0.0
        - 0.13
        radius: 0.01
      - center:
        - 0.001
        - -0.006
        - 0.045
        radius: 0.03
      gripper_r_base_link:
      - center:
        - -0.0
        - 0.003
        - 0.044
        radius: 0.02
      - center:
        - 0.001
        - -0.0
        - 0.087
        radius: 0.02
      - center:
        - 0.04
        - -0.013
        - 0.11
        radius: 0.01
      - center:
        - -0.053
        - -0.0
        - 0.129
        radius: 0.01
    cspace:
      acceleration_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      cspace_distance_weight:
      - 10.0
      - 10.0
      - 10.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      default_joint_position:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.2
      - 0.3
      - 2.07
      - -0.61
      - -1.57
      - 1.0
      - -1.57
      - -1.57
      - 1.57
      - -2.07
      - 0.61
      - 1.57
      - -1.0
      - 1.57
      - 1.57
      - -1.57
      - 0.0
      - 0.0
      - 0.5
      - 0.0
      - 0.0
      - 0.5
      - 0.0
      - 0.0
      jerk_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      joint_names:
      - dummy_base_prismatic_x_joint
      - dummy_base_prismatic_y_joint
      - dummy_base_revolute_z_joint
      - dummy_base_prismatic_x_joint
      - dummy_base_prismatic_y_joint
      - dummy_base_revolute_z_joint
      - idx01_body_joint1
      - idx02_body_joint2
      - idx21_arm_l_joint1
      - idx22_arm_l_joint2
      - idx23_arm_l_joint3
      - idx24_arm_l_joint4
      - idx25_arm_l_joint5
      - idx26_arm_l_joint6
      - idx27_arm_l_joint7
      - idx61_arm_r_joint1
      - idx62_arm_r_joint2
      - idx63_arm_r_joint3
      - idx64_arm_r_joint4
      - idx65_arm_r_joint5
      - idx66_arm_r_joint6
      - idx67_arm_r_joint7
      - idx11_head_joint1
      - idx12_head_joint2
      - idx41_gripper_l_outer_joint1
      - idx42_gripper_l_outer_joint3
      - idx32_gripper_l_inner_joint3
      - idx81_gripper_r_outer_joint1
      - idx82_gripper_r_outer_joint3
      - idx72_gripper_r_inner_joint3
      max_acceleration:
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      - 10.0
      max_jerk:
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      null_space_maximum_distance:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      null_space_weight:
      - 10.0
      - 10.0
      - 10.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      position_limit_clip: 0.0
      velocity_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    debug: null
    external_asset_path: null
    external_robot_configs_path: null
    extra_collision_spheres: null
    extra_links: {}
    format_version: 2.0
    grasp_contact_link_names: null
    load_meshes: false
    load_tool_frames_with_mesh: false
    lock_joints: {}
    mesh_link_names:
    - base_link
    - body_link1
    - body_link2
    - head_link1
    - head_link2
    - arm_l_base_link
    - arm_r_base_link
    - arm_l_link1
    - arm_l_link2
    - arm_l_link3
    - arm_l_link4
    - arm_l_link5
    - arm_l_link6
    - arm_l_end_link
    - arm_r_link1
    - arm_r_link2
    - arm_r_link3
    - arm_r_link4
    - arm_r_link5
    - arm_r_link6
    - arm_r_end_link
    - gripper_l_base_link
    - gripper_l_outer_link1
    - gripper_l_outer_link3
    - gripper_l_outer_link4
    - gripper_l_outer_link5
    - gripper_l_outer_link2
    - gripper_l_inner_link2
    - gripper_l_inner_link1
    - gripper_l_inner_link3
    - gripper_l_inner_link4
    - gripper_l_inner_link5
    - gripper_r_base_link
    - gripper_r_outer_link1
    - gripper_r_outer_link3
    - gripper_r_outer_link4
    - gripper_r_outer_link5
    - gripper_r_outer_link2
    - gripper_r_inner_link2
    - gripper_r_inner_link1
    - gripper_r_inner_link3
    - gripper_r_inner_link4
    - gripper_r_inner_link5
    self_collision_buffer:
      arm_l_base_link: 0.0
      arm_l_end_link: 0.0
      arm_l_link1: 0.0
      arm_l_link2: 0.0
      arm_l_link3: 0.0
      arm_l_link4: 0.0
      arm_l_link5: 0.0
      arm_l_link6: 0.0
      arm_r_base_link: 0.0
      arm_r_end_link: 0.0
      arm_r_link1: 0.0
      arm_r_link2: 0.0
      arm_r_link3: 0.0
      arm_r_link4: 0.0
      arm_r_link5: 0.0
      arm_r_link6: 0.0
      gripper_l_base_link: 0.0
      gripper_r_base_link: 0.0
    self_collision_ignore:
      arm_l_base_link:
      - arm_l_link1
      - arm_l_link2
      arm_l_link1:
      - arm_l_base_link
      - arm_l_link2
      - arm_l_link3
      arm_l_link2:
      - arm_l_base_link
      - arm_l_link1
      - arm_l_link3
      - arm_l_link4
      arm_l_link3:
      - arm_l_link1
      - arm_l_link2
      - arm_l_link4
      - arm_l_link5
      arm_l_link4:
      - arm_l_link2
      - arm_l_link3
      - arm_l_link5
      - arm_l_link6
      arm_l_link5:
      - arm_l_link3
      - arm_l_link4
      - arm_l_link6
      - arm_l_end_link
      arm_l_link6:
      - arm_l_link4
      - arm_l_link5
      - arm_l_end_link
      - gripper_l_base_link
      arm_l_end_link:
      - arm_l_link5
      - arm_l_link6
      - gripper_l_base_link
      gripper_l_base_link:
      - arm_l_link6
      - arm_l_end_link
      - arm_l_base_link
      - arm_l_link1
      - arm_l_link2
      - arm_l_link3
      - arm_l_link4
      - arm_l_link5
      arm_r_base_link:
      - arm_r_link1
      - arm_r_link2
      arm_r_link1:
      - arm_r_base_link
      - arm_r_link2
      - arm_r_link3
      arm_r_link2:
      - arm_r_base_link
      - arm_r_link1
      - arm_r_link3
      - arm_r_link4
      arm_r_link3:
      - arm_r_link1
      - arm_r_link2
      - arm_r_link4
      - arm_r_link5
      arm_r_link4:
      - arm_r_link2
      - arm_r_link3
      - arm_r_link5
      - arm_r_link6
      arm_r_link5:
      - arm_r_link3
      - arm_r_link4
      - arm_r_link6
      - arm_r_end_link
      arm_r_link6:
      - arm_r_link4
      - arm_r_link5
      - arm_r_end_link
      - gripper_r_base_link
      arm_r_end_link:
      - arm_r_link5
      - arm_r_link6
      - gripper_r_base_link
      gripper_r_base_link:
      - arm_r_link6
      - arm_r_end_link
      - arm_r_base_link
      - arm_r_link1
      - arm_r_link2
      - arm_r_link3
      - arm_r_link4
      - arm_r_link5
    tool_frames:
    - arm_l_end_link
    - arm_r_end_link
    urdf_path: robot/genie1/genie1.urdf
    use_external_assets: false
    use_global_cumul: true
  load_dynamics: false
