robot_cfg:
  kinematics:
    urdf_path: robot/vega_1p_sharpa/vega_1p_sharpa.urdf
    asset_root_path: robot/vega_1p_sharpa
    base_link: vega_1p_mobile
    tool_frames:
    - R_ee
    - L_ee
    collision_link_names:
    - vega_1p_base
    - vega_1p_torso_l1
    - vega_1p_torso_l2
    - vega_1p_torso_l3
    - vega_1p_head_l1
    - vega_1p_head_l2
    - vega_1p_head_l3
    - vega_1p_L_arm_l1
    - L_arm_l2
    - L_arm_l3
    - L_arm_l4
    - L_arm_l5
    - vega_1p_L_arm_l6
    - L_arm_l7
    - L_arm_l8
    - vega_1p_R_arm_l1
    - R_arm_l2
    - R_arm_l3
    - R_arm_l4
    - R_arm_l5
    - vega_1p_R_arm_l6
    - R_arm_l7
    - R_arm_l8
    - attached_object
    collision_spheres:
      vega_1p_base:
      - center:
        - 0.01462
        - -0.17787
        - 0.16
        radius: 0.11
      - center:
        - 0.21192
        - -0.08528
        - 0.15377
        radius: 0.11
      - center:
        - -0.00398
        - 0.16157
        - 0.18085
        radius: 0.11
      - center:
        - 0.14642
        - -0.20602
        - 0.17002
        radius: 0.11
      - center:
        - 0.23192
        - 0.03857
        - 0.15166
        radius: 0.11
      - center:
        - 0.15943
        - 0.16194
        - 0.19398
        radius: 0.11
      - center:
        - -0.20771
        - -0.13666
        - 0.12
        radius: 0.11
      - center:
        - -0.20137
        - 0.01171
        - 0.21135
        radius: 0.11
      - center:
        - -0.18175
        - 0.14136
        - 0.12
        radius: 0.11
      vega_1p_torso_l1:
      - center:
        - 0.114
        - -0.072
        - 0.025
        radius: 0.10435
      - center:
        - 0.254
        - -0.00595
        - 0.037
        radius: 0.135
      - center:
        - -0.006
        - -0.104
        - -0.009
        radius: 0.10502
      - center:
        - 0.101
        - 0.056
        - 0.011
        radius: 0.10502
      - center:
        - 0.002
        - 0.074
        - -0.002
        radius: 0.10167
      - center:
        - 0.415
        - -0.049
        - 0.069
        radius: 0.10301
      - center:
        - 0.413
        - 0.061
        - 0.06
        radius: 0.10234
      vega_1p_torso_l2:
      - center:
        - -0.17928
        - 0.00368
        - 0.03734
        radius: 0.095
      - center:
        - -0.40177
        - 0.02656
        - 0.0964
        radius: 0.095
      - center:
        - -0.28589
        - -0.0048
        - 0.05846
        radius: 0.095
      - center:
        - 0.00741
        - 0.00015
        - 0.00328
        radius: 0.11
      - center:
        - -0.08692
        - 0.00249
        - 0.01285
        radius: 0.1
      - center:
        - -0.39996
        - -0.05884
        - 0.09201
        radius: 0.095
      vega_1p_torso_l3:
      - center:
        - -0.077
        - -0.1055
        - 0.44
        radius: 0.0908
      - center:
        - -0.09128
        - 0.0405
        - 0.394
        radius: 0.09472
      - center:
        - -0.067
        - 0.0955
        - 0.434
        radius: 0.09472
      - center:
        - -0.08861
        - -0.0425
        - 0.407
        radius: 0.09472
      - center:
        - -0.026
        - -0.0025
        - 0.213
        radius: 0.08627
      - center:
        - -0.00259
        - 0.06507
        - 0.00471
        radius: 0.08759
      - center:
        - -0.05
        - -0.0035
        - 0.303
        radius: 0.08561
      - center:
        - -0.05
        - 0.0265
        - 0.097
        radius: 0.08298
      - center:
        - -0.043
        - -0.0365
        - 0.089
        radius: 0.08364
      - center:
        - -0.05
        - -0.0725
        - 0.126
        radius: 0.04891
      - center:
        - -0.048
        - 0.0685
        - 0.132
        radius: 0.04627
      - center:
        - 0.011
        - -0.0645
        - 0.061
        radius: 0.04891
      - center:
        - -0.008
        - 0.0705
        - 0.093
        radius: 0.04759
      - center:
        - -0.038
        - -0.0715
        - 0.004
        radius: 0.04891
      - center:
        - -0.045
        - 0.0665
        - 0.015
        radius: 0.04627
      - center:
        - -0.00137
        - -0.0634
        - 0.00063
        radius: 0.088
      vega_1p_head_l1:
      - center:
        - -0.003
        - 0.107
        - -0.018
        radius: 0.05527
      - center:
        - -0.0
        - 0.037
        - -0.015
        radius: 0.05456
      - center:
        - 0.003
        - 0.067
        - -0.036
        radius: 0.05456
      vega_1p_head_l2:
      - center:
        - -0.005
        - 0.033
        - 0.029
        radius: 0.05506
      - center:
        - -0.006
        - 0.004
        - 0.003
        radius: 0.05506
      - center:
        - -0.002
        - -0.039
        - 0.024
        radius: 0.05439
      vega_1p_head_l3:
      - center:
        - 0.013
        - -0.01175
        - 0.021
        radius: 0.07289
      - center:
        - 0.00412
        - 0.01725
        - 0.019
        radius: 0.07223
      vega_1p_L_arm_l1:
      - center:
        - 0.013
        - 0.01248
        - -0.01
        radius: 0.06497
      - center:
        - 0.03476
        - 0.05471
        - -0.00334
        radius: 0.077
      L_arm_l2:
      - center:
        - 0.00539
        - -0.0038
        - -0.043
        radius: 0.075
      - center:
        - 0.071
        - 0.008
        - -0.03112
        radius: 0.075
      - center:
        - 0.10232
        - 0.001
        - -0.03158
        radius: 0.075
      L_arm_l3:
      - center:
        - 0.021
        - -0.004
        - 0.001
        radius: 0.06
      - center:
        - 0.123
        - 0.003
        - 0.063
        radius: 0.06
      - center:
        - 0.074
        - 0.003
        - 0.017
        radius: 0.06
      L_arm_l4:
      - center:
        - 0.00361
        - -0.04506
        - -0.008
        radius: 0.07
      - center:
        - 0.1432
        - -0.041
        - -0.047
        radius: 0.065
      - center:
        - 0.04
        - -0.04802
        - -0.027
        radius: 0.065
      L_arm_l5:
      - center:
        - 0.01822
        - 0.00064
        - 0.005
        radius: 0.045
      - center:
        - 0.07068
        - -0.01836
        - -0.004
        radius: 0.045
      - center:
        - 0.069
        - 0.0048
        - -0.002
        radius: 0.045
      - center:
        - 0.029
        - 0.002
        - 0.003
        radius: 0.035
      vega_1p_L_arm_l6:
      - center:
        - 0.0663
        - -0.03108
        - 0.01
        radius: 0.04039
      - center:
        - 0.06474
        - -0.03233
        - -0.02
        radius: 0.04039
      - center:
        - 0.03131
        - -0.01938
        - -0.002
        radius: 0.04039
      - center:
        - -0.00836
        - -0.00503
        - 0.004
        radius: 0.04039
      L_arm_l7:
      - center:
        - 0.01103
        - 0.003
        - -0.016
        radius: 0.05
      - center:
        - 0.03948
        - 0.002
        - -0.029
        radius: 0.05
      L_arm_l8:
      - center:
        - 0.0
        - 0.0
        - -0.02209
        radius: 0.04
      vega_1p_R_arm_l1:
      - center:
        - -0.013
        - -0.01248
        - -0.01
        radius: 0.06497
      - center:
        - 0.03476
        - -0.05817
        - 0.00284
        radius: 0.077
      R_arm_l2:
      - center:
        - 0.00539
        - -0.0038
        - -0.043
        radius: 0.075
      - center:
        - 0.071
        - 0.008
        - -0.03112
        radius: 0.075
      - center:
        - 0.10232
        - 0.001
        - -0.03158
        radius: 0.075
      R_arm_l3:
      - center:
        - 0.021
        - -0.004
        - 0.001
        radius: 0.06
      - center:
        - 0.123
        - 0.003
        - 0.063
        radius: 0.06
      - center:
        - 0.074
        - 0.003
        - 0.017
        radius: 0.06
      R_arm_l4:
      - center:
        - 0.00361
        - -0.04506
        - -0.008
        radius: 0.07
      - center:
        - 0.1432
        - -0.041
        - -0.047
        radius: 0.065
      - center:
        - 0.04
        - -0.04802
        - -0.027
        radius: 0.065
      R_arm_l5:
      - center:
        - 0.01822
        - 0.00064
        - -0.00226
        radius: 0.045
      - center:
        - 0.07068
        - -0.00744
        - -0.004
        radius: 0.045
      - center:
        - 0.069
        - 0.02331
        - -0.002
        radius: 0.045
      - center:
        - 0.029
        - 0.002
        - 0.003
        radius: 0.035
      vega_1p_R_arm_l6:
      - center:
        - 0.0663
        - 0.03559
        - 0.01
        radius: 0.04039
      - center:
        - 0.06474
        - 0.0303
        - -0.02711
        radius: 0.04039
      - center:
        - 0.03131
        - 0.00537
        - -0.002
        radius: 0.04039
      - center:
        - -0.00644
        - 0.00352
        - 0.004
        radius: 0.04039
      R_arm_l7:
      - center:
        - 0.01103
        - 0.003
        - -0.016
        radius: 0.05
      - center:
        - 0.03948
        - 0.002
        - -0.029
        radius: 0.05
      R_arm_l8:
      - center:
        - 0.0
        - 0.0
        - -0.02209
        radius: 0.04
    self_collision_ignore:
      vega_1p_base:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      vega_1p_torso_l1:
      - vega_1p_base
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_head_l1
      - vega_1p_head_l2
      - vega_1p_head_l3
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_torso_l2:
      - vega_1p_base
      - vega_1p_torso_l1
      - vega_1p_torso_l3
      - vega_1p_head_l1
      - vega_1p_head_l2
      - vega_1p_head_l3
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_torso_l3:
      - vega_1p_base
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_head_l1
      - vega_1p_head_l2
      - vega_1p_head_l3
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_head_l1:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_head_l2
      - vega_1p_head_l3
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_head_l2:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_head_l1
      - vega_1p_head_l3
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_head_l3:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_head_l1
      - vega_1p_head_l2
      - vega_1p_L_arm_l1
      - vega_1p_R_arm_l1
      - L_arm_l2
      - R_arm_l2
      vega_1p_L_arm_l1:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_R_arm_l1
      - L_arm_l2
      - L_arm_l3
      L_arm_l2:
      - vega_1p_L_arm_l1
      - L_arm_l3
      - L_arm_l4
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      L_arm_l3:
      - L_arm_l2
      - L_arm_l4
      - L_arm_l5
      L_arm_l4:
      - L_arm_l3
      - L_arm_l5
      - vega_1p_L_arm_l6
      L_arm_l5:
      - L_arm_l4
      - vega_1p_L_arm_l6
      - L_arm_l7
      vega_1p_L_arm_l6:
      - L_arm_l5
      - L_arm_l7
      - L_arm_l8
      L_arm_l7:
      - vega_1p_L_arm_l6
      - L_arm_l8
      - attached_object
      L_arm_l8:
      - L_arm_l7
      - vega_1p_L_arm_l6
      - attached_object
      vega_1p_R_arm_l1:
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      - vega_1p_L_arm_l1
      - R_arm_l2
      - R_arm_l3
      R_arm_l2:
      - vega_1p_R_arm_l1
      - R_arm_l3
      - R_arm_l4
      - vega_1p_torso_l1
      - vega_1p_torso_l2
      - vega_1p_torso_l3
      R_arm_l3:
      - R_arm_l2
      - R_arm_l4
      - R_arm_l5
      R_arm_l4:
      - R_arm_l3
      - R_arm_l5
      - vega_1p_R_arm_l6
      R_arm_l5:
      - R_arm_l4
      - vega_1p_R_arm_l6
      - R_arm_l7
      vega_1p_R_arm_l6:
      - R_arm_l5
      - R_arm_l7
      - R_arm_l8
      R_arm_l7:
      - vega_1p_R_arm_l6
      - R_arm_l8
      - attached_object
      R_arm_l8:
      - R_arm_l7
      - vega_1p_R_arm_l6
      - attached_object
    self_collision_buffer:
      vega_1p_base: -0.05
      vega_1p_torso_l1: -0.05
      vega_1p_torso_l2: -0.05
      vega_1p_torso_l3: -0.03
      vega_1p_L_arm_l1: -0.02
      vega_1p_R_arm_l1: -0.02
      attached_object: 0.0
    lock_joints: {}
    extra_links:
      attached_object:
        parent_link_name: R_arm_l8
        link_name: attached_object
        fixed_transform:
        - 0
        - 0
        - 0
        - 1
        - 0
        - 0
        - 0
        joint_type: FIXED
        joint_name: attach_joint
    extra_collision_spheres:
      attached_object: 4
    collision_sphere_buffer: 0.0
    format_version: 2.0
    use_global_cumul: true
    add_object_link: false
    load_meshes: false
    load_tool_frames_with_mesh: false
    cspace:
      joint_names:
      - dummy_base_prismatic_x_joint
      - dummy_base_prismatic_y_joint
      - dummy_base_revolute_z_joint
      - torso_j1
      - torso_j2
      - torso_j3
      - head_j1
      - head_j2
      - head_j3
      - L_arm_j1
      - L_arm_j2
      - L_arm_j3
      - L_arm_j4
      - L_arm_j5
      - L_arm_j6
      - L_arm_j7
      - R_arm_j1
      - R_arm_j2
      - R_arm_j3
      - R_arm_j4
      - R_arm_j5
      - R_arm_j6
      - R_arm_j7
      null_space_weight:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      cspace_distance_weight:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      position_limit_clip: -0.2
      max_acceleration:
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      max_jerk:
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      - 500.0
      default_joint_position:
      - 0.0
      - 0.0
      - 0.0
      - 0.5
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      acceleration_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      velocity_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      jerk_scale:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      null_space_maximum_distance:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
  load_dynamics: false
